name: projector
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #connectivity: ^0.4.9+2
  cached_network_image: ^3.2.0
  credit_card_validator: null
  cupertino_icons: ^0.1.3
  collection: ^1.15.0
  dio: ^4.0.6
  dotted_border: ^1.0.6
  email_validator: ^1.0.6
  file_picker: ^4.5.1
  fluttertoast: ^7.0.2
  google_fonts: ^2.3.2
  http: ^0.13.4
  image_picker: ^0.8.6
  image_picker_android: ^0.8.4+11
  flutter_plugin_android_lifecycle: ^2.0.1
  lite_rolling_switch: ^0.1.1
  #lottie: ^0.7.0+1
  modal_progress_hud: ^0.1.3
  path_provider: ^2.0.2
  permission_handler: ^9.2.0
  photo_manager: ^0.6.0
  shared_preferences: ^2.0.6
  #stripe_payment: ^1.0.10
  url_launcher: null
  video_player: ^2.2.8
  video_thumbnail: ^0.5.0
  flutter_svg: ^0.19.3
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  app_tracking_transparency: ^2.0.2+1
  focused_menu: ^1.0.5
  #threading: ^0.0.8
  percent_indicator: ^4.0.0
  wakelock: ^0.6.1+2
  photo_view: ^0.13.0
  sizer: ^2.0.15
  new_version: ^0.3.1
  flutter_inappwebview: ^5.4.3+7
  smooth_page_indicator: ^1.0.0+2
  showcaseview: ^1.1.8
  firebase_crashlytics: ^2.8.9
  firebase_core: ^1.21.1
  flutter_uploader: ^3.0.0-beta.3
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/logoName.svg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-Black.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
